apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: execute-gcloud-job
  annotations:
    meta.crossplane.io/maintainer: Murph <murph@opusdavei.org>
    meta.crossplane.io/source: github.com/djeremiah/upbound-examples
    meta.crossplane.io/license: Apache-2.0
spec:
  crossplane:
    version: ">=v1.14.0-0"
  dependsOn:
    - provider: xpkg.upbound.io/crossplane-contrib/provider-kubernetes
      version: ">=v0.11.0"
    - provider: xpkg.upbound.io/upbound/provider-gcp-cloudrun
      version: ">=v0.41.0"

