apiVersion: aws.caas.upbound.io/v1alpha1
kind: Cluster
metadata:
  name: gitops-host
  namespace: default
spec:
  parameters:
    id: gitops-host
    region: eu-west-1
    version: "1.28"
    nodes:
      count: 3
      size: small
    serviceSelector: gitops-master
  writeConnectionSecretToRef:
    name: gitops-host-kubeconfig