apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata: 
  name: secretmanager
spec:
  writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: example.upbound.io/v1alpha1
    kind: XSecretManager
  resources:
  - name: secret
    base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: v1
            kind: Secret
            metadata:
              namespace: default
            stringData:
              one: hello
              two: world
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: metadata.annotations[argocd.argoproj.io/tracking-id]
      toFieldPath: spec.forProvider.manifest.metadata.annotations[argocd.argoproj.io/tracking-id]
      policy:
        fromFieldPath: Required
    connectionDetails:
    - type: FromFieldPath
      name: secret
      fromFieldPath: status.atProvider.manifest.metadata.name