apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata: 
  name: xsecretmanagers.example.upbound.io
spec: 
  group: example.upbound.io
  names: 
    kind: XSecretManager
    plural: xsecretmanagers
  claimNames: 
    kind: SecretManager
    plural: secretmanagers
  connectionSecretKeys:
  - secret
  versions: 
  - name: v1alpha1
    served: true
    referenceable: true
    schema: 
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties: {}
