apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xteams.example.upbound.io
spec:
  group: example.upbound.io
  names:
    kind: XTeam
    plural: xteams
  claimNames:
    kind: Team
    plural: teams
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties: {}
