apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: configuration-aws-lambda
  annotations:
    meta.crossplane.io/maintainer: Murph <murph@opusdavei.org>
    meta.crossplane.io/source: github.com/djeremiah/upbound-examples/serverless-apps
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      APIs for managing serverless applications on AWS Lambda
    meta.crossplane.io/readme: |
      This configuration presents a unified API for provisioning AWS Lambda Functions and connecting them to a variety of backing services.
spec:
  crossplane:
    version: ">=v1.11.0-0"
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-aws
      version: ">=v0.32.1"
    - provider: xpkg.upbound.io/crossplane-contrib/provider-helm
      version: ">=v0.14.0"
    