apiVersion: ansible.crossplane.io/v1alpha1
kind: AnsibleRun
metadata:
  name: crossplane-motd
spec:
  forProvider:
    vars:
      ansible_ssh_user: ec2-user
      ansible_become: true
      ansible_ssh_private_key_file: ./ssh_key
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    inventoryInline: |
      EC2 Instance External IP
    roles:
      - name: ansible_provider.crossplane_motd
        src: https://github.com/djeremiah/crossplane-motd.git