apiVersion: ansible.crossplane.io/v1alpha1
kind: AnsibleRun
metadata:
  name: ansible-touch
spec:
  forProvider:
    vars:
      ansible_ssh_user: ec2-user
      ansible_ssh_private_key_file: ./ssh_key
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    inventoryInline: |
      EC2 INSTANCE PUBLIC IP
    playbookInline: |
      ---
      - hosts: all
        become: true
        tasks:
          - name: Touch a file
            ansible.builtin.file:
              path: /etc/foo.conf
              state: touch
              mode: u+rw,g-wx,o-rwx
              modification_time: preserve
              access_time: preserve