apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xbuckets.example.upbound.io
spec:
  compositeTypeRef:
    apiVersion: example.upbound.io/v1alpha1
    kind: XBucket
  resources: 
  - name: bucket
    base: 
      apiVersion: s3.aws.upbound.io/v1beta1
      kind: Bucket
      spec:
        forProvider: 
          region: eu-west-1
    patches:
    - fromFieldPath: spec.parameters.bucketName
      toFieldPath: metadata.annotations[crossplane.io/external-name]
    - fromFieldPath: spec.forProvider
      toFieldPath: spec.forProvider
      policy:
        mergeOptions:
          keepMapValues: true