apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata: 
  name: xbuckets.example.upbound.io
spec:
  group: example.upbound.io
  names:
    kind: XBucket
    plural: xbuckets
  claimNames:
    kind: Bucket
    plural: buckets
  versions:
  - name: v1alpha1
    referenceable: true
    served: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters: 
                type: object
                properties: 
                  bucketName: 
                    type: string
              forProvider: 
                type: object 
                additionalProperties: 
                  x-kubernetes-preserve-unknown-fields: true
              
        