apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: exoduspoint
  annotations:
    meta.crossplane.io/maintainer: The Getting Started Organization <support@starter.org>
    meta.crossplane.io/source: github.com/djeremiah/exoduspoint
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      This starter configuration is completely empty.
    meta.crossplane.io/readme: |
      This starter configuration is completely empty, allowing you to start
      entirely from scratch.
spec:
  crossplane:
    version: ">=v1.12.0-0"
  dependsOn:
    - provider: xpkg.upbound.io/crossplane-contrib/provider-helm
      version: ">=v0.15.0"
    - provider: xpkg.upbound.io/crossplane-contrib/provider-kubernetes
      version: ">=v0.9.0"
    - provider: xpkg.upbound.io/upbound/provider-aws-ec2
      version: ">=v0.41.0"
    - provider: xpkg.upbound.io/upbound/provider-aws-eks
      version: ">=v0.41.0"
    - provider: xpkg.upbound.io/upbound/provider-aws-iam
      version: ">=v0.41.0"

