apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xproviders.example.upbound.io
spec:
  group: example.upbound.io
  names:
    kind: XProvider
    plural: xproviders
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  providerName:
                    type: string
                    description: Name of the provider to install
                  providerPkg:
                    type: string
                    description: URL of the provider package to install
              providerConfigRef:
                type: object
                properties:
                  name:
                    type: string
                    description: ProviderConfig to use for creating resources
                  